clear;
clf;
M = csvread('performance1000_100rep.csv');
plot(M(:, 1), M(:, 2));
hold on;
[a, b] = size(M);
x = 0:a;
plot(x, 0.000001*x.*log(x));
plot(x, 0.000001*x);
title('Fast Congruence Closure Implementation running 100 terms with 1000 repetitions');
xlabel('Number of terms used');
ylabel('Time in seconds');
legend('Running time of the algorithm', 'O(n*log(n)', 'O(n)');